**Problem - 1: Array Creation**

1. Initialize an empty array with size 2X2:

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print(empty_array)

[[3.40808159e-315 0.00000000e+000]
 [5.77005039e-317 5.76962351e-317]]


2. Initialize an all-one array with size 4X2:

In [ ]:
ones_array = np.ones((4, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value:

In [ ]:
filled_array = np.full((3, 3), 7)
print(filled_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array:

In [ ]:
zeros_like_array = np.zeros_like(np.array([[1, 2], [3, 4]]))
print(zeros_like_array)

[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array:

In [ ]:
ones_like_array = np.ones_like(np.array([[1, 2], [3, 4]]))
print(ones_like_array)

[[1 1]
 [1 1]]


6. Convert an existing list new_list = [1, 2, 3, 4] to a numpy array:

In [ ]:
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print(np_array)

[1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array Indexing**

1. Create an array with values ranging from 10 to 49:

In [ ]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8:

In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix:

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array:

In [ ]:
random_array = np.random.random(30)
mean = random_array.mean()
print(f"Mean: {mean}")

Mean: 0.5390342091656948


5. Create a 10X10 array with random values and find the minimum and maximum values:

In [ ]:
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print(f"Min: {min_val}, Max: {max_val}")

Min: 0.0678459311810482, Max: 0.9802522454924472


6. Create a zero array of size 10 and replace 5th element with 1:

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1, 2, 0, 0, 4, 0]:

In [ ]:
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.flip(arr)
print(reversed_arr)

[0 4 0 0 2 1]


8. Create a 2d array with 1 on the border and 0 inside:

In [ ]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create an 8X8 matrix and fill it with a checkerboard pattern:

In [ ]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations**

**For the following arrays:**

x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

Add the two arrays:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

addition_result = x + y
print(addition_result)

[[ 6  8]
 [10 13]]


Subtract the two arrays:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

subtraction_result = x - y
print(subtraction_result)

[[-4 -4]
 [-4 -3]]


Multiply the array with any integers of your choice:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

multiplication_result = x * 3
print(multiplication_result)

[[ 3  6]
 [ 9 15]]


Find the square of each element of the array:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

squared_result = np.square(x)
print(squared_result)

[[ 1  4]
 [ 9 25]]


Find the dot product between:

v and w

x and v

x and y

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print(f"Dot product of v and w: {dot_vw}")
print(f"Dot product of x and v: {dot_xv}")
print(f"Dot product of x and y: {dot_xy}")

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


6. Concatenate x and y along rows and concatenate v and w along columns:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print(concat_row)
print(concat_col)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


7. Concatenate x and v; if an error occurs, observe and explain:

In [ ]:
x = np.array([[1, 2], [3, 5]])

y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])

w = np.array([11, 12])

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print(f"Error: {e}")

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations**

**For the following arrays:**

A = np.array([[3, 4], [7, 8]])

B = np.array([[5, 3], [2, 1]])

1. Prove A * A^-1 = I:

In [ ]:
A = np.array([[3, 4], [7, 8]])

B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print(identity_matrix)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ≠ BA:

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print(f"AB: \n{AB}")
print(f"BA: \n{BA}")

AB: 
[[23 13]
 [51 29]]
BA: 
[[36 44]
 [13 16]]


3. Prove (AB)^T = B^T * A^T:

In [ ]:
transposed = np.transpose(np.dot(A, B))
transposed_check = np.dot(np.transpose(B), np.transpose(A))
print(f"(AB)^T: \n{transposed}")
print(f"B^T * A^T: \n{transposed_check}")

(AB)^T: 
[[23 51]
 [13 29]]
B^T * A^T: 
[[23 51]
 [13 29]]


4. Solve the system of linear equations using inverse methods:

In [ ]:
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])
X = np.linalg.inv(A_eq).dot(B_eq)
print(f"Solution to system: {X}")

Solution to system: [ 2.  1. -2.]


In [ ]:
X_linalg = np.linalg.solve(A_eq, B_eq)  # Use np.linalg.solve() to solve the system

print("Solution using np.linalg.solve:", X_linalg)

Solution using np.linalg.solve: [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**

**Element-wise Addition**

1. Using Python Lists:

In [ ]:
import time

# Create two lists of size 1,000,000
list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

# Measure time for element-wise addition using a loop
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(len(list1))]
end_time = time.time()

print(f"Time taken for Python list element-wise addition: {end_time - start_time:.5f} seconds")

Time taken for Python list element-wise addition: 0.16631 seconds


2. Using NumPy Arrays:

In [ ]:
import numpy as np

# Convert the lists into numpy arrays
array1 = np.array(list1)
array2 = np.array(list2)

# Measure time for element-wise addition using numpy
start_time = time.time()
result_numpy = array1 + array2
end_time = time.time()

print(f"Time taken for NumPy array element-wise addition: {end_time - start_time:.5f} seconds")

Time taken for NumPy array element-wise addition: 0.00515 seconds


**Element-wise Multiplication**

1. Using Python Lists:

In [ ]:
# Measure time for element-wise multiplication using a loop
start_time = time.time()
result_list_multiplication = [list1[i] * list2[i] for i in range(len(list1))]
end_time = time.time()

print(f"Time taken for Python list element-wise multiplication: {end_time - start_time:.5f} seconds")

Time taken for Python list element-wise multiplication: 0.12184 seconds


2. Using NumPy Arrays:

In [ ]:
# Measure time for element-wise multiplication using numpy
start_time = time.time()
result_numpy_multiplication = array1 * array2
end_time = time.time()

print(f"Time taken for NumPy array element-wise multiplication: {end_time - start_time:.5f} seconds")

Time taken for NumPy array element-wise multiplication: 0.00543 seconds


**Dot Product**

1. Using Python Lists:

In [ ]:
# Measure time for dot product using a loop
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end_time = time.time()

print(f"Time taken for Python list dot product: {end_time - start_time:.5f} seconds")

Time taken for Python list dot product: 0.11140 seconds


2. Using NumPy Arrays:

In [ ]:
# Measure time for dot product using numpy
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()

print(f"Time taken for NumPy array dot product: {end_time - start_time:.5f} seconds")

Time taken for NumPy array dot product: 0.00266 seconds


**Matrix Multiplication**

1. Using Python Lists:

In [ ]:
# Create two 1000x1000 matrices as lists of lists
matrix1 = [[i for i in range(1000)] for j in range(1000)]
matrix2 = [[i for i in range(1000)] for j in range(1000)]

# Measure time for matrix multiplication using nested loops
start_time = time.time()
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] for i in range(1000)]
end_time = time.time()

print(f"Time taken for Python list matrix multiplication: {end_time - start_time:.5f} seconds")

Time taken for Python list matrix multiplication: 190.30613 seconds


2. Using NumPy Arrays:

In [ ]:
# Create two 1000x1000 matrices as numpy arrays
matrix1_np = np.random.rand(1000, 1000)
matrix2_np = np.random.rand(1000, 1000)

# Measure time for matrix multiplication using numpy
start_time = time.time()
result_matrix_numpy = np.dot(matrix1_np, matrix2_np)
end_time = time.time()

print(f"Time taken for NumPy array matrix multiplication: {end_time - start_time:.5f} seconds")

Time taken for NumPy array matrix multiplication: 0.07202 seconds
